version: "2"
run:
    timeout: 3m
linters:
    default: all
    enable:
      - goconst
      - gocyclo
      - gosec
      - staticcheck
      - nilerr
      - prealloc
      - revive
      - staticcheck
      - unconvert
      - unused
      - whitespace
      - zerologlint
    exclusions:
        paths:
          - export_test.go
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - export_test.go
