version: "2"
run:
    timeout: 3m
linters:
    default: all
    enable:
      - goconst
      - gocyclo
      - gosec
      - staticcheck
      - nilerr
      - prealloc
      - revive
      - staticcheck
      - unconvert
      - unused
      - whitespace
      - zerologlint
      - wsl_v5
    settings:
        gocyclo:
            min-complexity: 13
        goconst:
            min-occurrences: 2
        wsl_v5:
          allow-first-in-block: true
          allow-whole-block: false
          branch-max-lines: 2 
        
    exclusions:
        paths:
          - export_test.go
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - export_test.go
