---
apiVersion: v1
kind: Template
metadata:
  name: ccx-insights-results-aggregator-cleaner
objects:

- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: insights-aggregator-cleaner
  spec:
    envName: ${ENV_NAME}
    testing:
      iqePlugin: ccx
    dependencies:
      - ccx-insights-results
    jobs:
      - name: cleaner
        schedule: ${JOB_SCHEDULE}
        restartPolicy: Never
        concurrencyPolicy: Forbid
        activeDeadlineSeconds: ${{DEADLINE_TIMEOUT}}
        podSpec:
          image: ${IMAGE}:${IMAGE_TAG}
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          env:
            - name: INSIGHTS_RESULTS_CLEANER__STORAGE__PG_PARAMS
              value: ${PG_PARAMS}
            - name: INSIGHTS_RESULTS_CLEANER__STORAGE__DB_DRIVER
              value: postgres
            - name: INSIGHTS_RESULTS_CLEANER__STORAGE__SCHEMA
              value: ocp_recommendations
            - name: INSIGHTS_RESULTS_CLEANER__LOGGING__DEBUG
              value: "${DEBUG}"
            - name: INSIGHTS_RESULTS_CLEANER__LOGGING__LOG_DEVEL
              value: "${LOG_LEVEL}"
            - name: INSIGHTS_RESULTS_CLEANER__CLEANER__MAX_AGE
              value: "${MAX_AGE}"
            - name: INSIGHTS_RESULTS_CLEANER__LOGGING__LOGGING_TO_SENTRY_ENABLED
              value: ${SENTRY_ENABLED}
            - name: INSIGHTS_RESULTS_CLEANER__SENTRY__DSN
              valueFrom:
                secretKeyRef:
                  key: dsn
                  name: insights-results-aggregator-cleaner-dsn
                  optional: true
            - name: INSIGHTS_RESULTS_CLEANER__SENTRY__ENVIRONMENT
              value: ${ENV_NAME}
          command:
            - ./insights-results-aggregator-cleaner
            - -dry-run=${DRY_RUN}
            - -cleanup-all=${CLEANUP_ALL}
    database:
      sharedDbAppName: ccx-insights-results

parameters:
- description: Image name
  name: IMAGE
  value: quay.io/redhat-services-prod/obsint-processing-tenant/insights-results-aggregator-cleaner/insights-results-aggregator-cleaner
- name: IMAGE_TAG
  required: true
  description: Image tag to use for apps
  value: latest
- description: Determines Clowder deployment
  name: CLOWDER_ENABLED
  value: "false"
- description: Env Name
  name: ENV_NAME
  required: true
- name: SUSPEND_JOB
  description: Should the cron job be disabled?
  value: "false"
- name: JOB_SCHEDULE
  description: When the cronjob runs
  value: "0 12 * * *"
- name: CPU_LIMIT
  description: Cpu limit of service
  value: 500m
- name: MEMORY_LIMIT
  description: memory limit of service
  value: 512Mi
- name: CPU_REQUEST
  description: Cpu request of service
  value: 200m
- name: MEMORY_REQUEST
  description: memory request of service
  value: 256Mi
- name: LOG_LEVEL
  description: Log level
  value: ""
- name: DEBUG
  value: "false"
- name: DATABASE_SERVICE_NAME
  required: true
  value: ccx-data-pipeline-db
- name: DEADLINE_TIMEOUT
  description: Deadline for the job execution
  value: "600"
- name: PG_PARAMS
  value: sslmode=require
- name: MAX_AGE
  description: Maximum age allowed to be kept in the database
  value: "90 days"
- name: DRY_RUN
  description: If true (default), the expected actions will be printed, but not executed into the database
  value: "true"
- name: CLEANUP_ALL
  description: If true (default), the program will be executed with the -cleanup-all argument, cleaning the database from old clusters
  value: "true"
- name: SENTRY_ENABLED
  value: "false"
